-- ============================================================================
-- BOOKS FEATURE — one-time Supabase setup
-- Run this in the Supabase SQL editor (Dashboard → SQL → New query).
-- Safe to re-run: everything is IF NOT EXISTS / idempotent.
-- ============================================================================

-- 1) CATALOG TABLE -----------------------------------------------------------
create table if not exists public.books (
  id           bigint generated by default as identity primary key,
  title        text not null,
  description  text,
  price        integer not null default 0,           -- INR; 0 when free
  free         boolean not null default false,
  cover_image  text,                                 -- public URL (book-covers)
  pdf_path     text,                                 -- path in private bucket (course-books)
  author       text,
  pages        integer,
  created_at   timestamptz not null default now()
);

alter table public.books enable row level security;

-- Anyone may read the catalog (note: SELECT list in the app never exposes pdf_path
-- to the public client; admin uses a separate query). pdf_path is only ever turned
-- into a download by the book-download edge function after a purchase check.
drop policy if exists "books are public" on public.books;
create policy "books are public"
  on public.books for select
  using (true);

-- Only admins may write.
drop policy if exists "admins manage books" on public.books;
create policy "admins manage books"
  on public.books for all
  using  (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true));


-- 2) PURCHASES (PERMANENT ENTITLEMENT) --------------------------------------
create table if not exists public.book_purchases (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  book_id      bigint not null references public.books(id) on delete cascade,
  payment_id   text,                                 -- null for free books
  purchased_at timestamptz not null default now(),
  unique (user_id, book_id)
);

alter table public.book_purchases enable row level security;

-- Buyers see only their own purchases.
drop policy if exists "users read own book purchases" on public.book_purchases;
create policy "users read own book purchases"
  on public.book_purchases for select
  using (auth.uid() = user_id);

-- Buyers may insert their own row (used for FREE books only; paid purchases are
-- written by the payment-verify edge function with the service role, which
-- bypasses RLS). A user can never insert a row for someone else.
drop policy if exists "users add own free book purchase" on public.book_purchases;
create policy "users add own free book purchase"
  on public.book_purchases for insert
  with check (auth.uid() = user_id);

-- Admins can read everything (for the admin dashboard).
drop policy if exists "admins read all book purchases" on public.book_purchases;
create policy "admins read all book purchases"
  on public.book_purchases for select
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true));


-- 3) STORAGE BUCKETS ---------------------------------------------------------
-- Public bucket for cover images.
insert into storage.buckets (id, name, public)
values ('book-covers', 'book-covers', true)
on conflict (id) do nothing;

-- PRIVATE bucket for the PDFs. Never public.
insert into storage.buckets (id, name, public)
values ('course-books', 'course-books', false)
on conflict (id) do nothing;

-- Covers: anyone can read; admins can write.
drop policy if exists "book covers public read" on storage.objects;
create policy "book covers public read"
  on storage.objects for select
  using (bucket_id = 'book-covers');

drop policy if exists "admins write book covers" on storage.objects;
create policy "admins write book covers"
  on storage.objects for all
  using  (bucket_id = 'book-covers' and exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true))
  with check (bucket_id = 'book-covers' and exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true));

-- Private PDFs: ONLY admins can upload/replace/delete via the client.
-- There is deliberately NO public/auth SELECT policy — reads happen exclusively
-- through short-lived signed URLs minted by the book-download edge function
-- (service role), which is not subject to these policies.
drop policy if exists "admins write course books" on storage.objects;
create policy "admins write course books"
  on storage.objects for all
  using  (bucket_id = 'course-books' and exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true))
  with check (bucket_id = 'course-books' and exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin = true));
